import { Technology } from '../types';

export const TECHNOLOGIES: Technology[] = [
  // --- LINGUAGENS & FUNDAMENTOS ---
  {
    id: 'python',
    name: 'Python',
    description: 'Aprenda uma das linguagens mais populares para Automação, Ciência de Dados, IA e Backend.',
    iconName: 'Terminal',
    color: '#22c55e',
    bgGradient: 'from-emerald-500/20 to-green-600/10 border-emerald-500/30',
    badge: 'Essencial',
    category: 'Linguagens',
  },
  {
    id: 'javascript',
    name: 'JavaScript',
    description: 'A linguagem fundamental da Web moderna para construir páginas dinâmicas, SPAs e lógica interativa.',
    iconName: 'Code',
    color: '#eab308',
    bgGradient: 'from-yellow-500/20 to-amber-600/10 border-yellow-500/30',
    badge: 'Base Web',
    category: 'Frontend',
  },
  {
    id: 'typescript',
    name: 'TypeScript',
    description: 'JavaScript com tipagem estática rigorosa, Generics, Interfaces avançadas e segurança em tempo de compilação.',
    iconName: 'Code2',
    color: '#3178c6',
    bgGradient: 'from-blue-600/20 to-indigo-700/10 border-blue-500/30',
    badge: 'Mercado',
    category: 'Linguagens',
  },

  // --- FRONTEND & FULLSTACK ---
  {
    id: 'react',
    name: 'React',
    description: 'Construa interfaces reativas e modulares com Hooks (useState, useEffect, useMemo), Custom Hooks e State Management.',
    iconName: 'Atom',
    color: '#06b6d4',
    bgGradient: 'from-cyan-500/20 to-blue-600/10 border-cyan-500/30',
    badge: 'Mais Pedido',
    category: 'Frontend',
  },
  {
    id: 'nextjs',
    name: 'Next.js Fullstack',
    description: 'Framework React com App Router, Server Actions, SSR, SSG, ISR, Otimização e deploy escalável.',
    iconName: 'Layers',
    color: '#e2e8f0',
    bgGradient: 'from-zinc-500/20 to-slate-700/10 border-zinc-500/30',
    badge: 'Fullstack',
    category: 'Frontend',
  },
  {
    id: 'html',
    name: 'HTML5 Semântico',
    description: 'A fundação da internet. Estruture documentos com tags semânticas, acessibilidade (a11y) e SEO.',
    iconName: 'Layout',
    color: '#f97316',
    bgGradient: 'from-orange-500/20 to-red-600/10 border-orange-500/30',
    badge: 'Base Web',
    category: 'Frontend',
  },
  {
    id: 'css',
    name: 'CSS3 & Tailwind',
    description: 'Estilização profissional com Flexbox, Grid, Animações, Responsividade Mobile-First e Tailwind CSS.',
    iconName: 'Palette',
    color: '#38bdf8',
    bgGradient: 'from-blue-500/20 to-cyan-600/10 border-blue-500/30',
    badge: 'Design',
    category: 'Frontend',
  },

  // --- BACKEND & APIS ---
  {
    id: 'nodejs',
    name: 'Node.js & Express',
    description: 'Servidores de alta performance com arquitetura assíncrona orientada a eventos e microsserviços.',
    iconName: 'Server',
    color: '#16a34a',
    bgGradient: 'from-green-700/20 to-emerald-800/10 border-green-700/30',
    badge: 'Backend',
    category: 'Backend',
  },
  {
    id: 'apis',
    name: 'APIs REST & GraphQL + Segurança',
    description: 'Design de APIs profissionais, autenticação JWT, OAuth2, Rate Limiting, OWASP Top 10 e documentação Swagger.',
    iconName: 'Network',
    color: '#ec4899',
    bgGradient: 'from-pink-500/20 to-rose-600/10 border-pink-500/30',
    badge: 'Arquitetura',
    category: 'Backend',
  },
  {
    id: 'python_fastapi',
    name: 'Python + Automação + FastAPI',
    description: 'APIs assíncronas ultrarrápidas com Pydantic, Web Scraping com BeautifulSoup/Playwright e tarefas em background.',
    iconName: 'Zap',
    color: '#10b981',
    bgGradient: 'from-emerald-500/20 to-teal-600/10 border-emerald-500/30',
    badge: 'Alta Velocidade',
    category: 'Backend',
  },
  {
    id: 'java',
    name: 'Java Enterprise & Spring',
    description: 'Linguagem corporativa sólida com Programação Orientada a Objetos, Design Patterns e ecossistema Spring.',
    iconName: 'Coffee',
    color: '#ea580c',
    bgGradient: 'from-amber-600/20 to-orange-700/10 border-orange-600/30',
    badge: 'Corporativo',
    category: 'Linguagens',
  },
  {
    id: 'php',
    name: 'PHP Moderno & Laravel',
    description: 'Sistemas web dinâmicos, MVC, APIs com Laravel e manipulação de formulários e bancos de dados.',
    iconName: 'Globe',
    color: '#a855f7',
    bgGradient: 'from-purple-500/20 to-indigo-600/10 border-purple-500/30',
    badge: 'Sistemas Web',
    category: 'Backend',
  },

  // --- MOBILE ---
  {
    id: 'flutter',
    name: 'Flutter & Dart Mobile',
    description: 'Desenvolvimento multiplataforma nativo para Android e iOS com UI responsiva e gerenciamento de estado.',
    iconName: 'Smartphone',
    color: '#0284c7',
    bgGradient: 'from-sky-400/20 to-blue-500/10 border-sky-400/30',
    badge: 'Mobile App',
    category: 'Mobile',
  },

  // --- BANCO DE DADOS ---
  {
    id: 'postgresql',
    name: 'PostgreSQL + Arquitetura + Segurança + Testes',
    description: 'Bancos de dados avançados, Índices B-Tree/GIN, EXPLAIN ANALYZE, Row-Level Security (RLS), Transações ACID e Testes.',
    iconName: 'Database',
    color: '#336791',
    bgGradient: 'from-sky-700/20 to-indigo-900/10 border-sky-600/30',
    badge: 'Enterprise SQL',
    category: 'Banco de Dados',
  },
  {
    id: 'mysql',
    name: 'MySQL Relacional',
    description: 'Modelagem relacional, queries SQL avançadas, JOINs, chaves estrangeiras, triggers e otimização.',
    iconName: 'HardDrive',
    color: '#00758f',
    bgGradient: 'from-cyan-800/20 to-blue-900/10 border-cyan-700/30',
    badge: 'Relacional',
    category: 'Banco de Dados',
  },

  // --- CYBERSECURITY & SISTEMAS ---
  {
    id: 'linux_cyber',
    name: 'Linux para Cybersecurity & Ethical Hacking',
    description: 'Linha de comando Bash, Permissões & ACLs, Reconhecimento de redes (Nmap), Análise de logs e Privilege Escalation.',
    iconName: 'ShieldAlert',
    color: '#ef4444',
    bgGradient: 'from-red-600/20 to-rose-700/10 border-red-500/30',
    badge: 'Hacking Ético',
    category: 'Cybersecurity',
  },
  {
    id: 'c_sys_cyber',
    name: 'C + Redes + SO + Cybersecurity',
    description: 'Ponteiros e gerenciamento de memória, Sockets TCP/UDP, Análise de Buffer Overflow, Chamadas de Sistema e Shellcode.',
    iconName: 'Cpu',
    color: '#6366f1',
    bgGradient: 'from-indigo-600/20 to-purple-700/10 border-indigo-500/30',
    badge: 'Low-Level & Sec',
    category: 'Cybersecurity',
  },

  // --- DEVOPS, CLOUD & IA ---
  {
    id: 'cloud_devops',
    name: 'Go → Rust → Cloud & DevOps',
    description: 'Concorrência em Go, Segurança de memória em Rust, Docker, Kubernetes, Pipelines CI/CD e Observabilidade.',
    iconName: 'Cloud',
    color: '#00add8',
    bgGradient: 'from-cyan-600/20 to-teal-700/10 border-cyan-500/30',
    badge: 'Cloud Native',
    category: 'DevOps & Cloud',
  },
  {
    id: 'ai_apps',
    name: 'IA + APIs de IA + Aplicações Inteligentes',
    description: 'Engenharia de Prompts, Integração de LLMs (Gemini / OpenAI), Embeddings, Busca Vetorial, RAG e Agentes Autônomos.',
    iconName: 'Sparkles',
    color: '#8b5cf6',
    bgGradient: 'from-purple-600/20 to-violet-700/10 border-purple-500/30',
    badge: 'IA Generativa',
    category: 'IA & Dados',
  },

  // --- FERRAMENTAS & SOFT SKILLS ---
  {
    id: 'git',
    name: 'Git & GitHub Profissional',
    description: 'Controle de versão, Branches (GitFlow / Trunk-based), Rebase vs Merge, Resolução de conflitos e CI/CD com GitHub Actions.',
    iconName: 'GitBranch',
    color: '#f05032',
    bgGradient: 'from-orange-600/20 to-red-600/10 border-orange-500/30',
    badge: 'Colaboração',
    category: 'Ferramentas',
  },
  {
    id: 'english_tech',
    name: 'Inglês Técnico para Devs & Segurança',
    description: 'Vocabulário essencial para documentação técnica, RFCs, OWASP, Code Reviews, leitura de CVEs e entrevistas internacionais.',
    iconName: 'BookMarked',
    color: '#f59e0b',
    bgGradient: 'from-amber-500/20 to-yellow-600/10 border-amber-500/30',
    badge: 'Carreira Global',
    category: 'Carreira & Inglês',
  },
  // --- GAME DEVELOPMENT & 3D ---
  {
    id: 'unity_2d',
    name: 'C# → Unity → Jogos 2D',
    description: 'Do Pong e Flappy Bird ao Platformer, Top-down shooter e RPG 2D com física 2D, Tilemaps e C#.',
    iconName: 'Gamepad2',
    color: '#00c853',
    bgGradient: 'from-emerald-600/20 to-teal-700/10 border-emerald-500/30',
    badge: 'Game Dev 2D',
    category: 'Game Dev',
  },
  {
    id: 'unity_3d',
    name: 'Unity 3D + Blender + C#',
    description: 'Criação de jogos 3D completos: FPS simples, Third-Person, Racing game, Survival e Open-World pequeno com Iluminação e Física.',
    iconName: 'Box',
    color: '#3b82f6',
    bgGradient: 'from-blue-600/20 to-cyan-700/10 border-blue-500/30',
    badge: 'Game Dev 3D',
    category: 'Game Dev',
  },
  {
    id: 'unreal_cpp',
    name: 'Unreal Engine 5 + C++ & Blueprints',
    description: 'Desenvolvimento AAA com C++, Blueprints, Nanite, Lumen, Shaders, Game Framework, AI Perception e Otimização.',
    iconName: 'Layers',
    color: '#8b5cf6',
    bgGradient: 'from-violet-600/20 to-purple-700/10 border-violet-500/30',
    badge: 'AAA Engine',
    category: 'Game Dev',
  },
  {
    id: 'godot_engine',
    name: 'Godot Engine 4 & GDScript / C#',
    description: 'Motor aberto moderno: arquitetura de Nós e Cenas, GDScript 2.0, Física 2D/3D Jolt, Shaders e exportação multiplataforma rápida.',
    iconName: 'Cpu',
    color: '#478cbf',
    bgGradient: 'from-sky-600/20 to-blue-700/10 border-sky-500/30',
    badge: 'Open Source',
    category: '3D & Engines',
  },
  {
    id: 'game_multiplayer',
    name: 'Multiplayer & Game Networking',
    description: 'TCP/IP vs UDP, Servidor Autoritativo, Replicação, Client-Side Prediction, Lag Compensation, Matchmaking e Anti-Cheat.',
    iconName: 'Network',
    color: '#f59e0b',
    bgGradient: 'from-amber-600/20 to-orange-700/10 border-amber-500/30',
    badge: 'Multiplayer',
    category: 'Game Dev',
  },
  {
    id: 'game_mobile_dev',
    name: 'Mobile Game Development',
    description: 'Android SDK, Gradle, AAB, Google Play Console, Controles Touch, Safe Area, Otimização Térmica/Bateria e Monetização IAP/Ads.',
    iconName: 'Smartphone',
    color: '#10b981',
    bgGradient: 'from-emerald-500/20 to-green-600/10 border-emerald-500/30',
    badge: 'Mobile Games',
    category: 'Game Dev',
  },
  {
    id: 'game_pc_publishing',
    name: 'Windows, Steam & Publicação',
    description: 'Builds x64, Gamepad / XInput, Save Systems, Steamworks SDK (Conquistas, Steam Cloud), Inno Setup e Lançamento na Steam.',
    iconName: 'Globe',
    color: '#06b6d4',
    bgGradient: 'from-cyan-600/20 to-sky-700/10 border-cyan-500/30',
    badge: 'Publicação',
    category: 'Game Dev',
  },
  {
    id: 'game_fundamentals',
    name: 'Fundamentos: Matemática & Física para Games',
    description: 'Álgebra Linear (Vetores, Dot/Cross Product), Algoritmo A*, Particionamento Espacial (Quadtrees/Octrees) e Motores de Física 2D.',
    iconName: 'Zap',
    color: '#ec4899',
    bgGradient: 'from-pink-600/20 to-rose-700/10 border-pink-500/30',
    badge: 'Matemática & CS',
    category: 'Game Dev',
  },
  {
    id: 'game_graphics_ai',
    name: 'Especialização: Game AI, Shaders & Performance',
    description: 'Pipeline gráfico da GPU, Shaders HLSL/GLSL, IA com GOAP e Utility Curves, Frame Pacing e Profiling de Draw Calls.',
    iconName: 'Sparkles',
    color: '#d946ef',
    bgGradient: 'from-fuchsia-600/20 to-pink-700/10 border-fuchsia-500/30',
    badge: 'Avançado',
    category: 'Game Dev',
  },
  {
    id: 'blender_3d',
    name: 'Blender 3D para Game Dev',
    description: 'Modelagem 3D Low-Poly, Mapeamento UV, Texturas PBR, Rigging, Animações para Jogos e Pipeline de Exportação FBX / glTF.',
    iconName: 'Palette',
    color: '#ea580c',
    bgGradient: 'from-orange-600/20 to-amber-700/10 border-orange-500/30',
    badge: 'Modelagem 3D',
    category: '3D & Engines',
  },
];
